version: '3.3'

services:

  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - APP_URL=http://localhost:8500 /* localhost or ip */
      - MYSQL_PORT_3306_TCP_ADDR=mariadb   
      - MYSQL_PORT_3306_TCP_PORT=3306     
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=change_me /* change password */
    volumes:
      - ./snipe_data:/config
    ports:
      - "8500:80"
    depends_on:
      - mariadb     
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    hostname: mariadb    
    environment:
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=change_me /* change username */
      - MYSQL_ROOT_PASSWORD=change_me  /* change password */
      - TZ="PST/PDT"
      - PUID=1000
      - PGID=1000      
    volumes:
      - ./snipe_db:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
